name: Cache-Cache
version: '1.1'
main: fr.cel.cachecache.CacheCache
api-version: '1.20'
authors: [ Cel, Deadsky666 ]
depend: [Hub]
commands:
  cachecache:
    description: La commande principale du plugin